spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt-security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

#application:
#  security:
#    jwt:
#      secret-key: 8f15bbfdd567e137221779f4c16a58b9314d0360f7c520b7ad390a226eb027a0
#      expiration: 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days